package org.give2peer.karma.response;

import org.give2peer.karma.entity.User;

/**
 * Populated by the response to POST /users
 */
public class RegistrationResponse
{
    /**
     * The user created by the registration
     */
    User user;

    /**
     * Is only present in the response when one was generated by the server.
     */
    String password;


    public User getUser()                    { return user;                                        }

    public void setUser(User user)           { this.user = user;                                   }

    public String getPassword()              { return password;                                    }

    public void setPassword(String password) { this.password = password;                           }

}
