package org.give2peer.karma.response;

import org.give2peer.karma.entity.User;

/**
 * Populated by the response to POST /users
 */
public class RegistrationResponse
{

    /**
     * The user created by the registration
     */
    User user;

    /**
     * Is only present in the response when one was generated by the server.
     */
    String password;

}
